os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git ../flutter -b beta --depth 1
  - ../flutter/bin/flutter doctor
language: generic
jobs:
  include:
    - stage: test
      language: generic
      script:
        - $(../flutter/bin/cache/dart-sdk/bin/dartfmt -n lib)
        - ../flutter/bin/flutter analyze
        - ../flutter/bin/flutter test
    - stage: deploy
      language: android
      android:
        # The BuildTools version used by your project
        - build-tools-28.0.2
        # The SDK version used to compile your project
        - android-27
        # Sys image for eventual virtual devices
        - sys-img-armeabi-v7a-android-26
      script: ../flutter/bin/flutter -v build apk
cache:
  directories:
  - $HOME/.pub-cache

