language: generic
os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6
      - fonts-droid
jobs:
  include:
    - stage: prepare cache
      script:
        - git clone https://github.com/flutter/flutter.git $HOME/flutter -b beta --depth 1
        - $HOME/flutter/bin/flutter doctor
    - stage: test
      script: $HOME/flutter/bin/cache/dart-sdk/bin/dartfmt -n lib
    - stage: test
      script: $HOME/flutter/flutter/bin/flutter analyze
    - stage: test
      script: $HOME/flutter/flutter/bin/flutter test
cache:
  directories:
  - $HOME/.pub-cache
  - $HOME/flutter
